-- MySQL Script generated by MySQL Workbench
-- 07/08/16 09:08:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schedule_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schedule_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schedule_db` DEFAULT CHARACTER SET utf8 ;
USE `schedule_db` ;

-- -----------------------------------------------------
-- Table `schedule_db`.`SCHEDULE_DB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule_db`.`SCHEDULE_DB` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATE` DATETIME NOT NULL,
  `APPOINTMENT` VARCHAR(140) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
